import turtle as t
from random import randint
t.bgcolor("Black")
t.screensize(1000,2000)
t.title("Dream")
def circ():         #displays the circle part of the mandala
    cir=t.Turtle()
    cir.pensize(2)
    cir.speed(0)
    cir.hideturtle()
    cir.color ("red","black")
    cir.penup()
    cir.goto(0,-30)
    cir.pendown()
    cir.circle(100,360)
    cir.penup()
    cir.goto(0,-35)
    cir.pendown()
    cir.color ("blue","black")
    cir.circle(105,360)
    cir.penup()
    cir.goto(0,-85)
    cir.pendown()
    cir.color ("pink","black")
    cir.circle(155,360)
    cir.penup()
    cir.goto(0,70)
    cir.pendown()
    for i in range(8):
        cir.color("white","black")
        cir.circle(25)
        cir.right(45)

def sqr(): #displays the square part of the mandala
    sqr=t.Turtle()
    sqr.pensize(2)
    sqr.hideturtle()
    sqr.speed(0)
    def atcirc():   #displays the circle at the sides of the first square
        sqr.penup()
        sqr.forward(50)
        sqr.left(70)
        sqr.forward(70)
        sqr.pendown()
        sqr.circle(15,360)   
        sqr.penup()
        sqr.right(0)
        sqr.backward(70)
        sqr.left(110)
        sqr.forward(50)
        sqr.pendown()
        sqr.right(180)
    def atcirc2():  #displays the circle at the corner of the square
        sqr.penup()
        sqr.forward(20)
        sqr.left(30)
        sqr.forward(45)
        sqr.pendown()
        sqr.circle(15,360)
        sqr.penup()
        sqr.right(0)
        sqr.backward(45)
        sqr.left(150)
        sqr.forward(20)
        sqr.pendown()
        sqr.right(180)
    sqr.color ("yellow","black")
    sqr.penup()
    sqr.goto(-76,5)
    sqr.pendown()
    for i in range(2): #1st square
        sqr.forward(150)
        atcirc()
        sqr.left(90)
        sqr.forward(130)
        atcirc()
        sqr.left(90)
    sqr.penup()
    sqr.goto(-30,-25)
    sqr.pendown()
    sqr.left(30)
    for i in range(2): #seconds square
        sqr.forward(145)
        sqr.left(90)
        sqr.forward(135)
        sqr.left(90)
    sqr.penup()
    sqr.goto(29,-25)
    sqr.pendown()
    sqr.left(30)
    for i in range(2): #3rd square
        sqr.forward(135)
        atcirc2()
        sqr.left(90)
        sqr.forward(145)
        atcirc2()
        sqr.left(90)

def tri(): #displays the multi color triangle part of the mandala
    tri=t.Turtle()
    tri.pensize(2)
    tri.hideturtle()
    tri.color ("#fffdd0","black")
    tri.speed(0)
    tri.penup()
    tri.goto(-300,-85)
    tri.pendown()
    for i in range(72):
            r=randint(30,255)
            g=randint(30,255)
            b=randint(30,255)
            t.colormode(255)
            tri.forward(600)
            tri.left(125)
            tri.color(r,g,b)


circ()
sqr()
tri()
t.exitonclick()
